---
- name: Download nvm script
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh
    dest: "{{ home_dir }}/nvm-install.sh"
    mode: 500

- name: Run nvm script
  shell: "{{ home_dir }}/nvm-install.sh"

- name: Install npm 8.11.2
  shell: . $NVM_DIR/nvm.sh && nvm install 8.11.2
  args:
      executable: /bin/bash
- name: Install “pg-migrator” node.js package.
  npm:
    name: pg-migrator
    global: yes